### ISSUE TITLE
False Discovery Rates and C - Statistics

### ISSUE THREAD

**Issue by iamciera** [DiscoveryDNA/team_neural_network#25]
**NEEDS to be done**

-  [x] We need a better way to assess accuracy. It is not all about getting the highest validation accuracy.  We need to get the false discovery rates and c-statistics.  We need to build this into our scripts, create confusion matrices, and create documentation.
- [x] Present to group the code and what the statistics mean

**Comment by iamciera** [comment]
Can you run on: `https://github.com/DiscoveryDNA/team_neural_network/blob/master/code/2018-07-29_pointing_out_a_fault_in_previous_experiments.ipynb`

**Comment by zhanyuanucb** [comment]
**A script for calculating the FDR and C-statistics of a model:**
https://github.com/DiscoveryDNA/team_neural_network/blob/master/code/utility/FDR_and_C_stats.ipynb

**Apply the FDR-C-statistics script on a model:** https://github.com/DiscoveryDNA/team_neural_network/blob/master/code/729model_FDR_and_C_stats.ipynb
