### ISSUE TITLE
New Data Formats: Project 2 Multiclassification

### ISSUE THREAD

**Issue by iamciera** [DiscoveryDNA/team_neural_network#26]
## New data formats

The most energy and creativity for machine learning projects is on organizing the data, optimizing the data structures, and extracting features. That being said, the current data structure is not what we will using in the future.

See below projects and pick which seems most interesting to you. A good strategy would be to use only a small subset of the data to start messing with, run experiments & test accuracy and then and only then, make the whole dataset and run on a larger machine. 

-   **Project 2**: Multiclassification of the current work. The coolest part of this dataset is that these sequences are classified on multiple stages, but this information is not being used. The file used to attach classification information to the sequences is here: [classification_table3_21Aug2018.csv](https://github.com/DiscoveryDNA/team_neural_network/blob/master/data/input/classification_table3_21Aug2018.csv).

**Comment by adfost** [comment]
Working on this issue.

**Comment by iamciera** [comment]
You add yourself using the top right corner.  I added you myself. Please link to your code that you used for merging when you get a chance.
